### ISSUE TITLE
도전장 보내고 이탈시 도전장 받는 사람이 수락이 가능한 문제

### ISSUE THREAD

**Issue by Jay13Jeong** [Jay13Jeong/PinguPong#155]
1. 유저 A와 B가 있다.
2. A가 도전장을 보내고 로비로 가거나 이탈한다.
3. B가 도착한 도전장을 열고 수락한다.
4. 게임이 진행된다.

수행이 안되도록 막아야합니다.

**Comment by FeFe2200** [comment]
#159 에서 해결 완료
