### ISSUE TITLE
채팅 : DM 기능 만들기

### ISSUE THREAD

**Issue by FeFe2200** [Jay13Jeong/PinguPong#23]
채팅 : DM 기능 만들기

**Comment by Jay13Jeong** [comment]
채팅구현 업무 to do list git이슈 하나로 통합해 주세요

**Comment by yoouyeon** [comment]
채팅 관련해서 추가로 구현 필요한 / 논의해봐야 할 기능입니다. (이미 구현되어있다면 알려주세요...)
- 추방 (서브젝트 표현으로는 kick) 기능
  - 추방시키기 기능
  - 추방당한 쪽에도 이를 알려야 합니다.)
- 추방 후 채팅 입장 금지 (서브젝트 표현으로는 ban) 기능 구현 여부 확실히 정하기
- 해당 유저가 현재 음소거인지 여부를 확인하는 기능
- 서브젝트 Security concerns 부분의 내용이 저희 채팅방 password에 적용되어 있는지... 확인해봐야 할 것 같습니다.
 Any password stored in your database **must be hashed**. (출처: 서브젝트 4페이지)
- 비밀방을 공개방으로 / 공개방을 비밀방으로 바꾸는 기능이 필요한 것 같습니다 .... 😭
 **The channel owner can set a password** required to access the channel, change it, and also **remove it**. (출처: 서브젝트 5페이지)

**Comment by FeFe2200** [comment]
비밀번호 추후 DB 사용시 설정 예정
비밀방을 공개방으로 / 공개방을 비밀방으로 바꾸는 기능은 비밀번호 설정시 여부를 변경하는 것으로 하겠습니다

**Comment by FeFe2200** [comment]
디엠 기능 완성
