### ISSUE TITLE
채팅 : 유일한 참가자의 소켓연결이 끊겼다가 다시 연결되었을 때의 문제

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/PinguPong#55]
## 문제 상황
1. 방을 새로 생성하여 입장
2. 뒤로 가기를 눌러 채팅 목록 창으로 돌아감
3. 새로고침을 누른 경우
3-1. 채팅방 목록에서 채팅방이 사라짐
4. 새로고침을 누르지 않은 경우
4-1. 채팅방 목록에 채팅방이 여전히 있음
4-2. 버튼을 누르면 입장이 가능함.

## 예상 원인 / 해결 방안
1. 소켓 연결이 끊겼으므로 방에서 유저를 삭제, 유일한 참가자가 사라졌으므로 방이 사라져서 다시 방에 들어가려고 시도할 때 문제가 생기는 것 같습니다. 소켓 연결이 끊겼을 때에 방에서 유저를 삭제하고 연결 시에 재등록하는 방식이 좋은 방법인지 다시 한번 생각해 봐야 할 것 같습니다. 😩
2. 존재하지 않는 방에 입장이 가능합니다... 방이 존재하는지 여부를 확인하는 과정이 필요할 것 같습니다. (목록이 실시간으로 업데이트 되지 않음)

**Comment by FeFe2200** [comment]
예상원인/ 해결방안에서
1번의 경우 유저를 소켓 Id 값이 아닌 유저Id 값으로 들어가도록 수정 완료
2번의 경우 추가 테스트 필요

**Comment by FeFe2200** [comment]
2번의 경우 목록리스트에 있는 방이 서버에서는 사라진 경우, 접속할 때 생기는 문제로, 비밀번호 여부 확인뒤 getUser 이벤트에서 예외처리 완료
