### ISSUE TITLE
핑퐁 : 게임 매치 신청이 회수되지 않는 문제

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/PinguPong#56]
## 문제상황
<img width="769" alt="Screen Shot 2023-02-04 at 4 36 58 PM" src="https://user-images.githubusercontent.com/57761286/216755311-176f37ca-2af0-4276-b3b6-b72d5c36c5e2.png">

## 예상 원인 / 해결 방안
1. 소켓 이벤트 리스너를 회수하지 않아서 생기는 문제로 예상됨.. cleanup 처리를 완료하고 다시 확인해봐야 할 것 같습니다.
2. 위의 문제와는 별개로 **게임 매치 요청 취소** 기능을 추가하는 것이 좋을 것 같네요..

**Comment by FeFe2200** [comment]
예상 원인 / 해결 방안에서
1번은 A가 메인화면으로 돌아가면 매칭 회수가 되도록 수정완료
